name: Deploy React App to Azure Web Apps

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Step 0. Login to Azure
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: id-token

    # Step 1. Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2. Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    # Step 3. Install dependencies
    - name: Install dependencies
      working-directory: ./project
      run: npm install

    # Step 4. Build the React app
    - name: Build the React app
      working-directory: ./project
      run: npm run build

    # Step 5. Deploy the app to Azure Web Apps
    - name: Deploy the app to Azure Web Apps
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'i-meant-to-be-web'
        package: ./project/dist

    # Step 6. Logout from Azure
    - name: Logout from Azure
      run: az logout