name: Build and deploy (main)

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 0. Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2. Create .env file based on GitHub environment variables
      - name: Setup .env
        working-directory: ./project
        run: echo "${{ vars.ENV }}" > .env

      # Step 3. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 4. Install dependencies
      - name: Install dependencies
        working-directory: ./project
        run: npm install

      # Step 5. Build the React app
      - name: Build the React app
        working-directory: ./project
        run: npm run build

      # Step 6. Deploy the app to Azure Web Apps
      - name: Deploy the app to Azure Web Apps
        uses: azure/webapps-deploy@v3
        with:
          app-name: "i-meant-to-be-web"
          package: ./project/dist

      # Step 7. Logout from Azure
      - name: Logout from Azure
        run: az logout

  rebase:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout dev branch
        run: git checkout dev

      - name: Rebase dev onto main
        run: git rebase origin/main

      - name: Force push updated dev branch
        run: git push origin dev --force-with-lease
